
title: Milkshake Apps
email:
description:  "App that make you life shake"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://milkshakeapps.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
sass:
  sass_dir: _sass
  style: compressed
include:
  - '_pages'
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
navigation:
  - title: Home
    url: /

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
